# Generated by Django 4.0.3 on 2022-03-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_log_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlist',
            name='launched_at',
            field=models.DateTimeField(null=True),
        ),
    ]
