# Generated by Django 4.0.3 on 2022-03-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaignlist_launched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaign.campaignlist'),
        ),
    ]
