# Generated by Django 4.0.3 on 2022-03-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_log_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignlist',
            name='launched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
