# Generated by Django 4.0.3 on 2022-03-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_victim_email_alter_victim_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='first_name',
            field=models.CharField(blank=True, default=' ', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='last_name',
            field=models.CharField(blank=True, default=' ', max_length=70, null=True),
        ),
    ]
