# Generated by Django 4.0.3 on 2022-03-26 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0001_initial'),
        ('mainapp', '0005_alter_victim_first_name_alter_victim_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='email_list.list'),
            preserve_default=False,
        ),
    ]
