# Generated by Django 4.0.3 on 2022-03-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_victim_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
