# Generated by Django 4.0.3 on 2022-03-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0005_templatelist_from_mail_templatelist_subject'),
        ('mainapp', '0007_alter_victim_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_list.list'),
        ),
    ]
