# Generated by Django 4.0.3 on 2022-03-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0002_category_list_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='template_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
