# Generated by Django 4.0.3 on 2022-03-26 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0003_list_template_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='template_body',
        ),
        migrations.CreateModel(
            name='TemplateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('template_body', models.TextField(blank=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_list.category')),
            ],
        ),
    ]
