# Generated by Django 4.0.3 on 2022-03-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0004_remove_list_template_body_templatelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelist',
            name='from_mail',
            field=models.CharField(default='Trisha Teresa <trisha@devlink.click>', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatelist',
            name='subject',
            field=models.CharField(default='New Subject', max_length=200),
        ),
    ]
