# Generated by Django 4.0.3 on 2022-03-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0005_templatelist_from_mail_templatelist_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatelist',
            name='cat',
        ),
    ]
