# Generated by Django 4.0.3 on 2022-03-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0006_remove_templatelist_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
