# Generated by Django 4.0.3 on 2022-03-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_victim_list'),
        ('campaign', '0003_campaignlist_launched_at'),
        ('email_list', '0007_remove_list_cat_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='EmailList',
        ),
    ]
