# Generated by Django 4.0.3 on 2022-07-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='3', max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='page_number',
            field=models.CharField(default='2', max_length=155),
            preserve_default=False,
        ),
    ]
