# Generated by Django 4.0.3 on 2022-07-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_author_book_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
