# Generated by Django 4.0.3 on 2022-06-19 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_book_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.department'),
            preserve_default=False,
        ),
    ]
