# Generated by Django 4.0.3 on 2022-06-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_book_student_options_book_student_date_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_student',
            options={'verbose_name': 'Book n Student', 'verbose_name_plural': 'Books n Students'},
        ),
    ]
