# Generated by Django 4.0.3 on 2022-07-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_bookstudent_is_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstudent',
            name='fine',
            field=models.FloatField(default=0),
        ),
    ]
